version: "2.3"
services:
  digital-market-fe:
    build:
      context: ../digital-market-fe
      dockerfile: ./Dockerfile
    ports:
      - 3321:3321
    volumes:
      - ../digital-market-fe:/digital-market-fe
    container_name: digital-market-fe
    networks:
      - nuxt-network
  digital-market-serive:
    build:
      context: ../digital-market-service
      dockerfile: ./Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ../digital-market-service:/digital-market-service
    container_name: digital-market-service
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: digital-market
      MYSQL_PASSWORD: Rg2mcVPg
      MYSQL_ROOT_PASSWORD: Rg2mcVPg
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql/mysql:/var/lib/mysql
      - ./sql/mysql-dump:/var/backups
    ports:
      - 127.0.0.1:3311:3306
    container_name: mysql
volumes:
  sk_mysql_data:
    driver: local

networks:
  nuxt-network:
    driver: bridge
